export const initConstants = {
  GETCAT_REQUEST: "GETCAT_REQUEST",
  GETCAT_SUCCESS: "GETCAT_SUCCESS",
  GETCAT_FAILURE: "GETCAT_FAILURE",

  GETLOC_REQUEST: "GETLOC_REQUEST",
  GETLOC_SUCCESS: "GETLOC_SUCCESS",
  GETLOC_FAILURE: "GETLOC_FAILURE",
};

export const authConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  WATCH_REQUEST: "WATCH_REQUEST",
  WATCH_SUCCESS: "WATCH_SUCCESS",
  WATCH_FAILURE: "WATCH_FAILURE",

  ARCHIVE_SUCCESS: "ARCHIVE_SUCCESS",

  // EDITPROFILE_REQUEST: "EDITPROFILE_REQUEST",
  // EDITPROFILE_SUCCESS: "EDITPROFILE_SUCCESS",
  // EDITPROFILE_FAILURE: "EDITPROFILE_FAILURE",

  // EDITPASS_REQUEST: "EDITPASS_REQUEST",
  // EDITPASS_SUCCESS: "EDITPASS_SUCCESS",
  // EDITPASS_FAILURE: "EDITPASS_FAILURE",

  // RESETPASS_REQUEST: "RESETPASS_REQUEST",
  // RESETPASS_SUCCESS: "RESETPASS_SUCCESS",
  // RESETPASS_FAILURE: "RESETPASS_FAILURE",
};

export const postConstants = {
  GETPOST_REQUEST: "GETPOST_REQUEST",
  GETPOST_SUCCESS: "GETPOST_SUCCESS",
  GETPOST_FAILURE: "GETPOST_FAILURE",

  GETEXTRAPOST_SUCCESS: "GETEXTRAPOST_SUCCESS",
  GETEXTRAPOST_FAILURE: "GETEXTRAPOST_FAILURE",

  POST_REQUEST: "POST_REQUEST",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAILURE: "POST_FAILURE",
  POST_SHOW_RESULT: "POST_SHOW_RESULT",
  POST_HIDE_RESULT: "POST_HIDE_RESULT",
};
