export const authConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  EDITPROFILE_REQUEST: "EDITPROFILE_REQUEST",
  EDITPROFILE_SUCCESS: "EDITPROFILE_SUCCESS",
  EDITPROFILE_FAILURE: "EDITPROFILE_FAILURE",

  EDITPASS_REQUEST: "EDITPASS_REQUEST",
  EDITPASS_SUCCESS: "EDITPASS_SUCCESS",
  EDITPASS_FAILURE: "EDITPASS_FAILURE",

  RESETPASS_REQUEST: "RESETPASS_REQUEST",
  RESETPASS_SUCCESS: "RESETPASS_SUCCESS",
  RESETPASS_FAILURE: "RESETPASS_FAILURE",
};
