export const initConstants = {
  GETCAT_REQUEST: "GETCAT_REQUEST",
  GETCAT_SUCCESS: "GETCAT_SUCCESS",
  GETCAT_FAILURE: "GETCAT_FAILURE",

  GETLOC_REQUEST: "GETLOC_REQUEST",
  GETLOC_SUCCESS: "GETLOC_SUCCESS",
  GETLOC_FAILURE: "GETLOC_FAILURE",
};

export const authConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  // EDITPROFILE_REQUEST: "EDITPROFILE_REQUEST",
  // EDITPROFILE_SUCCESS: "EDITPROFILE_SUCCESS",
  // EDITPROFILE_FAILURE: "EDITPROFILE_FAILURE",

  // EDITPASS_REQUEST: "EDITPASS_REQUEST",
  // EDITPASS_SUCCESS: "EDITPASS_SUCCESS",
  // EDITPASS_FAILURE: "EDITPASS_FAILURE",

  // RESETPASS_REQUEST: "RESETPASS_REQUEST",
  // RESETPASS_SUCCESS: "RESETPASS_SUCCESS",
  // RESETPASS_FAILURE: "RESETPASS_FAILURE",
};

export const postConstants = {
  GETPOST_REQUEST: "GETPOST_REQUEST",
  GETPOST_SUCCESS: "GETPOST_SUCCESS",
  GETPOST_FAILURE: "GETPOST_FAILURE",

  NEWPOST_REQUEST: "NEWPOST_REQUEST",
  NEWPOST_SUCCESS: "NEWPOST_SUCCESS",
  NEWPOST_FAILURE: "NEWPOST_FAILURE",
  NEWPOST_SHOW_RESULT: "NEWPOST_SHOW_RESULT",
  NEWPOST_HIDE_RESULT: "NEWPOST_HIDE_RESULT",
};
